
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: postgresql
  password: root
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: test_app_development

test:
  <<: *default
  database: test_app_test

#
production:
  <<: *default
  database: test_app_production
  # username: test_app
  # password:

staging:
  <<: *default
  database: test_app_staging
