# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34db783c704883377d8f5a68aebdf9c4aa587d10afebb7b1f5701b5f1fa48f51e5fdf56221898857190922b2fa45db5b905bf0270f9c7bf8a2fe7c86717a28f8

test:
  secret_key_base: 51ca412b0fe648547ebf271ab42b6a8c3d165d761a5a9c1aa0f0639ab48d0ab2d0de453cb29dfd4aeaf4294d881cb6957931aa3c86be247629a37ef542a89171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
